/* 12. Find the total revenue generated by each employee */

select e.first_name , e.last_name ,sum(unit_price * quantity - (unit_price * quantity * discount)) As "revenue" from employees e left join orders o 
On e.employee_id = o.employee_id
Inner join order_details o_d
On o.order_id = o_d.order_id
inner join products p 
On p.product_id= o_d.product_id
group by e.employee_id;
